### ISSUE TITLE
"Your Details" label in header seems confusing, what should it be?

### ISSUE THREAD

**Issue by jarofgreen** [OpenACalendar/OpenACalendar-Web-Core#316]
This gives you access to your account.
But it also gives logged out people the option to set timezone, if applicable.

![welcome - open a calendar demo master](https://cloud.githubusercontent.com/assets/85656/6059608/b282b146-ad2b-11e4-8704-cf906ca6d0cf.png)

Suggestions please? We might decide to leave it the same but let's discuss ....

**Comment by tfgg** [comment]
I'd have found the "sign up" option much quicker if it was just a separate link in the top right corner for logged out users.

I generally found the drop down menus quite difficult to discover, since there's no indication that they drop down (e.g. a little arrow next to them).

**Comment by jarofgreen** [comment]
So it would need "sign up / Log in"?
If you were trying to change the timezone you were viewing the calendar in, were would you expect to find that? (I know that doesn't apply to MeetYourNextMP but gotta think about that ....)

**Comment by tfgg** [comment]
Yes, that or a single "log in" link that would also include a sign up form if you're unregistered, which is a reasonably common pattern. It just took some thinking to realise "your details" meant logging in/registering.

I'm not sure I would expect to be able to set the time zone anywhere (maybe next to the calendar itself so it is in eyeshot?). You could combine it with an indicator of the current time zone, which when clicked lets you change the timezone.

**Comment by farwall** [comment]
Account / Settings would be my best guess if you're going to keep the timezone thing grouped in there.

**Comment by jarofgreen** [comment]
Ok, so "sign up / Log in" if logged out with links to change timezone on page. I think we'll try that. I think with the timezone thing grouped in, it's just to hard to pick a good label. Thanks for commenting :-)

On MeetYourNextMP soon, on other sites later ......
