### ISSUE TITLE
When user adding or editing event, show nice date range text

### ISSUE THREAD

**Issue by jarofgreen** [OpenACalendar/OpenACalendar-Web-Core#372]
Easier to parse

![add an event - test1 open a calendar master](https://cloud.githubusercontent.com/assets/85656/6771143/8d332d46-d0ce-11e4-8e8c-44dceb090874.png)

**Comment by JoeMitchell** [comment]
Cool, perhaps could be a little easier to read by doing <b> Tue 1 Dec </b> (drop the 'st'), then a hyphen, then the non-bold time?

**Comment by jarofgreen** [comment]
That's done on new event and edit event, will sit on overnight and put live tomorrow.

Thoughts: some kinda loading indictar needed, or gray out old date time while loading?

> Tue 1 Dec (drop the 'st'), then a hyphen, then the non-bold time?

I like the "st" - no? Will ask around. Will have a think on rest. Good start tho. Thanks for push.
