### ISSUE TITLE
Events out by an hour

### ISSUE THREAD

**Issue by terminalpixel** [OpenACalendar/OpenACalendar-Web-Core#418]
Our ICS file is being imported fine https://www.dundeemakerspace.co.uk/events/?ical=1&tribe_display=list but events are listed an hour out on https://opentechcalendar.co.uk/group/209-dundee-makerspace

**Comment by jarofgreen** [comment]
Timezone just changed on source file; check again later

**Comment by jarofgreen** [comment]
https://twitter.com/dundeemakespace/status/656425490459316224 Is fine now, still will double check feed .. at some point
