### ISSUE TITLE
Meet up import not picking up cancellations

### ISSUE THREAD

**Issue by jarofgreen** [OpenACalendar/OpenACalendar-Web-Core#465]
See Python Edinburgh

**Comment by judy2k** [comment]
Hi! The meetup has a default of "Pub Meetup - Let's Talk Python!" (or something similar). I usually change it at some point between 2 months and 2 weeks before the actual event to what is specifically happening.

In this case, the event was actually a dojo, and I changed it... quite a while ago, I think. The reminder that Meetup sent out a week ago certainly had the correct details.

**Comment by jarofgreen** [comment]
https://opentechcalendar.co.uk/importurl/88 has not run for a month as it had expired. I'm reactivating it now, and I will check back shortly and go over it thoroughly.

**Comment by jarofgreen** [comment]
https://opentechcalendar.co.uk/event/3361-pub-night-lets-talk-python Links to http://www.meetup.com/Python-Edinburgh/events/226130431/ which is fine

https://opentechcalendar.co.uk/event/3190-pub-night-lets-talk-python links to http://www.meetup.com/Python-Edinburgh/events/qzzvqkytpbgc/ which now doesn't exist. (Deleted manually)

Both events are for same date. Did the event for Nov get deleted and recreated?

Need to see what API is returning for this - I'm working today but will look into ASAP.

**Comment by judy2k** [comment]
I edited the existing, recurring event and specified I was only editing the one occurrence.

If this is like Google calendar it creates an exception rule in the recurring event and then a new one-off event to hold the modified data. I fell foul of that on an earlier Python Edinburgh website.

**Comment by jarofgreen** [comment]
If you create a recurring event in Meetup, you actually get separate (but linked) events with different IDs in the API & Web. An approach I think is actually sensible, we do something similar.

(Oddly, Meetup sometimes seem to use a numeric event ID and sometimes a string one. Oddly the events with numeric ID's actually have a string IDs to - eg, see https://www.meetup.com/Python-Edinburgh/events/fhgxklytpbgc/ No idea what the difference means. I should probably ignore that. But wonder if it's something to do with recurring events.)

I suspect one issue is that Meetup has a status field with options: "cancelled", "upcoming", "past", "proposed", "suggested" or "draft" - note no deleted. If an event is deleted, it probably just vanishes. At the moment we aren't doing anything to detect events that just vanish, I think.

Not sure of data issues at this point. Going to watch feed, both on live and dev box.

**Comment by jarofgreen** [comment]
Added which may help with this: https://github.com/OpenACalendar/OpenACalendar-Web-Core/issues/472
