### ISSUE TITLE
Menus should close when you click off them

### ISSUE THREAD

**Issue by GregSutcliffe** [OpenACalendar/OpenACalendar-Web-Core#576]
Steps to reproduce:

1. Click Events to open menu
2. Click somewhere else on page

Expected behaviour: menu closes
Actual behaviour: it doesn't ;)

**Comment by jarofgreen** [comment]
Done. Already on http://demomasterss.openacalendar.org/

Should have done this ages ago ,thanks for prodding

**Comment by jarofgreen** [comment]
Oh wait, issue with this. If Menu A is open and you click header for Menu B

Expect: Menu A to close, Menu B to open (old Behaviour)
What happens now: Menu A close, Menu B nothing

Not sure how to fix this immediately. It's on OTC to ....

**Comment by GregSutcliffe** [comment]
True. It's still an improvement over the old behaviour though :)
