### ISSUE TITLE
Setting site logo fails in singlesite mode

### ISSUE THREAD

**Issue by GregSutcliffe** [OpenACalendar/OpenACalendar-Web-Core#580]
Clicking "Make site logo" on an image's media page results in

... script '/srv/OpenACalendar/webSingleSite/getLogo.php' not found .. 

in the Apache logs. This seems to exist in "/webSite/getLogo.php" but even after copying that into the above path I still get a "Whoops" page with no further logs - suggestions on debugging?

**Comment by jarofgreen** [comment]
Technically, the error is easy to fix but I'm wondering if the "make site logo" feature A) was designed to and/or B) should work in Multi Site mode only, not Single Site.

Either way, there is work to do here. (if answer is yes, need to hide that option in single site mode.)

In the mean time, if you have your own extension you can add the file /theme/default/img/site/logo.png and when you build assets it should use your image.

**Comment by GregSutcliffe** [comment]
Fair enough, I'll leave that up to you. Setting the logo from the extension does indeed work, as does the favicon. It;s sahping up nicely as a demo... :)

**Comment by jarofgreen** [comment]
Looking at code, intention was this should only work in Multi Site mode. So for now, that's what we'll follow.
