### ISSUE TITLE
cancelled events should be shown as such in the index

### ISSUE THREAD

**Issue by GregSutcliffe** [OpenACalendar/OpenACalendar-Web-Core#585]
Currently (1.6) if you cancel an event, it clearly displays

"This event has been cancelled!"

On the Show page for the event. However, the index page only changes the black date/time box to "cancelled" which is easy to miss. The event title should probably have "[cancelled]" added to it for clarity

**Comment by jarofgreen** [comment]
Done. Also for Deleted to.
Also, currently event show page only puts Cancelled in header - added Deleted to.

**Comment by GregSutcliffe** [comment]
Awesome - although deleted events don't show in the index anyway, right?

**Comment by jarofgreen** [comment]
There is a search filter for deleted events

**Comment by GregSutcliffe** [comment]
ah right, of course. good stuff!
