### ISSUE TITLE
Delete action in show page should be delete/cancel

### ISSUE THREAD

**Issue by GregSutcliffe** [OpenACalendar/OpenACalendar-Web-Core#586]
Currently there's no indication to an organiser that an event has the option to be cancelled - it;s only when you click the Delete action that it expands to show the Cancel and Delete options.

I think there's two ways to solve this. The obvious one is to make that entry "Cancel/Delete" - but this may be too hard on screen real estate. The other is to switch to "Cancel" as the top-level acton, with delete hidden underneath - I think it's more intuitive that way around (could just be me though). Even when wishing to delete an bad event, "cancelling" it makes some sense and I might click that, and thus see the delete option in the menu, whereas delete makes no sense to me if I wish to simply mark an event as cancelled.

**Comment by jarofgreen** [comment]
To be honest, from seeing data from a popular import source about this I suspect many peoples ideas about when to delete vs cancel are odd anyway. Some informal user testing around this may be good. Good point to raise tho, thanks.

**Comment by GregSutcliffe** [comment]
Yeah, my gut feeling is that real delete is a rare occurrence - usually only immediately after creation when you realise that you've done something completely stupid. 99% of the time you want to cancel an upcoming event, and that *absolutely* should not just disappear from people's calendars without warning.

**Comment by GregSutcliffe** [comment]
For the record, this was based on feedback from my single event-adder. She got quite confused between cancel and delete, and even I had to play with both to get to a point where I could give her a good explanation (which lead to #585 while playing around)

**Comment by jarofgreen** [comment]
How about:

- Neither cancel or delete as menu headers
- When click on edit, "Cancel" is one of the options in the menu
- Cancel page has current cancel form and text at bottom "You can also delete" with link to delete form

Try and guide them to cancel. But show them delete is available and try and explain difference when appropriate without cluttering up main UI.

Only worry
- Someone who def wanted to delete would look at menu and go "How do I delete? I don't want to cancel!" and then not find delete. But then surely most people would think "well I'll cancel then" and go to cancel? Or would some get annoyed and not delete or cancel?

**Comment by GregSutcliffe** [comment]
I think that works, yes. You can't please everyone, but I suspect the percentage of people who wouldn't at least *try* cancel *or* read the docs is acceptably low ;)

**Comment by jarofgreen** [comment]
Will think.

Note: If event is cancelled, have to show delete link in "edit" menu or elsewhere.

**Comment by jarofgreen** [comment]
Think way to do this is so:

-     Neither cancel or delete as menu headers
-     When click on edit, "Cancel/delete" is one of the options in the menu, at bottom.
-     Cancel page has current cancel form and text at bottom "You can also delete" with link to delete form

That solves issue with someone not finding delete I raised earlier but still guides ppl to cancel rather than delete. Will do.
