### ISSUE TITLE
Method for highlighting ticketed events

### ISSUE THREAD

**Issue by GregSutcliffe** [OpenACalendar/OpenACalendar-Web-Core#603]
This was raised by my users - there's a significant difference between a show-up-for-free event, a pay-at-the-door event, and a must-book-ahead event. The latter, in particular, requires more advance planning - and the calendar should be able to warn of that.

Right now, we have the Tickets URL, or a custom tag. Neither show up on the event list or the calendar pop up, only on the event show page.

Thoughts?

**Comment by jarofgreen** [comment]
How would you define such events, simply on if there is a ticket URL or not? Would it be enough to show a little ticket icon if there is a tickets URL?

What I'm wondering is, is that enough or is there more distinguishing between different type of events with ticket URLs that is needed.

**Comment by GregSutcliffe** [comment]
I think that's a good first pass - the key is that we show all the information needed to decide *not* to find out more info up front (I don't mind clicking through to an event I'm interested in, but after 5 events I can't go to because it's *tomorrow* and I don't have a ticket, I'll get bored).

The other option is a separate checkbox, but thats more work for potentially small gains.

**Comment by jarofgreen** [comment]
What label would this be accompanied by? I went with "See information about tickets". That's very vague, but actually it's harder to go further.

Started on separate branch, while work out details.

So when logged in, here is the event list page:

![screen shot 2016-05-13 at 20 39 30](https://cloud.githubusercontent.com/assets/85656/15259725/e3cb1f72-194a-11e6-95a2-e053f3a72188.png)

I'm pretty happy with this one. One of the things we want to do is when someone says they will attend on our site, make sure they see original ticket link. So we are not taking over the other event.

Here's when logged out:

![screen shot 2016-05-13 at 20 41 18](https://cloud.githubusercontent.com/assets/85656/15259759/12db260e-194b-11e6-9e53-6ea22927be8c.png)

Less happy with this one. It takes up a whole line for one small icon. Not sure what to do.

Calendar:

![screen shot 2016-05-13 at 20 42 06](https://cloud.githubusercontent.com/assets/85656/15259783/31e38302-194b-11e6-8546-7ba205179fd6.png)

Question is; what should be in calendar popup? Link to URL and Ticket URL of event? If so, we should also link to our event page, but what labels to use to be clear about difference? Maybe:

- "More Information"
- "More Information from _domain_"
- "Tickets from _domain_"

**Comment by GregSutcliffe** [comment]
> What label would this be accompanied by? I went with "See information about tickets". That's very vague, but actually it's harder to go further.

Sounds fine

> Started on separate branch, while work out details.

I'll take a look when I have some time.

> So when logged in, here is the event list page:
> I'm pretty happy with this one. One of the things we want to do is when someone says they will attend on our site, make sure they see original ticket link. So we are not taking over the other event.

Sounds and looks good.

> Here's when logged out:
> Less happy with this one. It takes up a whole line for one small icon. Not sure what to do.

Is there a technical reason preventing the ticket icon being on the same line as the location? Seems it could sit to the left of the pin quite nicely...

> Calendar:

That looks nice.

> Question is; what should be in calendar popup? Link to URL and Ticket URL of event? If so, we should also link to our event page, but what labels to use to be clear about difference? Maybe:

    "More Information"
    "More Information from domain"
    "Tickets from domain"

"Buy tickets" directly under "More details" would be my shout, linking directly to the ticket URL. That way if people are unsure and want more details, there's the original link; but if they've no need of more info (perhaps a ticket for a recurring event) then they can save themselves a few clicks.

Good stuff so far!

**Comment by jarofgreen** [comment]
> Is there a technical reason preventing the ticket icon being on the same line as the location? Seems it could sit to the left of the pin quite nicely...

See, with that tho that means some address would be indented in a little bit and some wouldn't. It would be nice if they all lined up when looking down list. For events with a ticket, we could have a blank space so all addresses lined up - but then the left edge of the location wouldn't line up with the left of the description. Will think ....

> "Buy tickets" directly under "More details" would be my shout

So you would just have "More details", "Buy tickets", only 2? Hmmm ..... maybe.

**Comment by GregSutcliffe** [comment]
Hmm, yes, identations... you could put the optional ticket icon *after* the location though.... As for the calendar popup, yes, just 2. I don't think it makes sense to crowd the popup (especially with mobile in mind) and I can't think of many usecases which wouldn't be served by one of those two links.

**Comment by jarofgreen** [comment]
Oh, thinking of putting ticket icon after description, on same line. 

But then would we have ticket in "attending" line for logged in users to? Or would that only appear if they said they might/would attend - to remind them to get a ticket.

**Comment by GregSutcliffe** [comment]
Hmm, too many options, I'm losing track of the proposals now... :) - are we talking about the calendar popup or the list entry here?

I'll try to fire up the `issue603` branch later this week and see where it's at - I'm sure I can find the appropriate file to hack on to try a few things out and/or look at what seems right from my perspective. Screenshots are making this much easier to debate for sure, so I'll see if I can get some of my own ;)

**Comment by jarofgreen** [comment]
Ok, so here is calendar popup:

![screen shot 2016-05-19 at 10 44 31](https://cloud.githubusercontent.com/assets/85656/15389423/b9175f08-1dae-11e6-8a3a-d570352b9b3d.png)

(Those two links will be styled as buttons when merged.)

Here's an event listing when logged in. Ticket is in same place when logged out. 

![screen shot 2016-05-19 at 11 36 11](https://cloud.githubusercontent.com/assets/85656/15390840/f6d02fda-1db5-11e6-8f84-08836444fc29.png)

If your logged in and you check your options:

![screen shot 2016-05-19 at 11 37 35](https://cloud.githubusercontent.com/assets/85656/15390863/1f57a1cc-1db6-11e6-8dfb-48ee10e75692.png)

But if you say you are or might attend:

![screen shot 2016-05-19 at 11 38 11](https://cloud.githubusercontent.com/assets/85656/15390879/32ca7504-1db6-11e6-851d-805c00b1ced9.png)

I think .... this is now good, tho I may want to double check how that last screenshot looks on mobile. It's one long line and touch zones might end up to close together. On mobile, probably break it into sections vertically with some space.  Might do this as separate ticket as this is prob an issue already!

Will leave to think, but want to merge back in next few days.

**Comment by GregSutcliffe** [comment]
pretty damn near perfect, I'd say! The *only* thing I can say (and it's minor, so feel free to ignore) is  that having the ticket icon at the end of the description could be missed when everything else is in the status line. If possible, I'd put it next to the attendance icon - ":ticket: :attending: You [choice] attending ..." if you see what I mean.

As i say, thats minor though, so ignore or postpostpone to a future issue/patch if you prefer.

Good stuff!

**Comment by jarofgreen** [comment]
That attending line only comes up if the user is logged in tho. For logged out users, it needs to go elsewhere. That's why it's on the description, as both logged in and out users see that.

**Comment by GregSutcliffe** [comment]
Ah yes. ok, drop that for now and lets see what the feedback is first

**Comment by jarofgreen** [comment]
![screen shot 2016-05-20 at 07 32 00](https://cloud.githubusercontent.com/assets/85656/15419324/fcd53cb6-1e5c-11e6-9d30-77d08af7a5e7.png)

Pushed down for basic responsive, merged!

**Comment by GregSutcliffe** [comment]
Packages built, will give it a whirl tonight :)
