### ISSUE TITLE
Make site creation db script idempotent

### ISSUE THREAD

**Issue by GregSutcliffe** [OpenACalendar/OpenACalendar-Web-Core#606]
I'm currently working on packaging OpenACalendar for Debian Jessie (and it's nearly done, as a first cut, yay!)

Currently the setup steps involve these four scripts:
* php5 core/cli/upgradeDatabase.php                                                    
* php5 core/cli/loadStaticData.php                                                     
* php5 core/cli/createUser.php admin admin@`hostname -f` 12345678 sysadmin             
* php5 core/cli/createSite.php site admin@`hostname -f`                                

I'm fairly certain the first 2 are safe to run repeatedly (so I don't have to try and detect upgrades versus new installs of the package). The third will correctly say `That name is already taken`. However, the last one will bomb completely:

```
# php core/cli/createSite.php site admin@test2foo
Slug: site
Email: admin@test2foo
Can any verified user edit: false
Starting ...
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "site_slug"
DETAIL:  Key (slug)=(site) already exists.' in /usr/share/openacalendar/core/php/repositories/SiteRepository.php:82
Stack trace:
#0 /usr/share/openacalendar/core/php/repositories/SiteRepository.php(82): PDOStatement->execute(Array)
#1 /usr/share/openacalendar/core/cli/createSite.php(78): repositories\SiteRepository->create(Object(models\SiteModel), Object(models\UserAccountModel), Array, Object(models\SiteQuotaModel), false)
#2 {main}
  thrown in /usr/share/openacalendar/core/php/repositories/SiteRepository.php on line 82
```

Any chance we can make it gracefully re-usable? It will greatly simplify the packages if these steps can be run on any install/upgrade. The alternatives are ... messy :)

**Comment by jarofgreen** [comment]
Obvs, we need to clear up the error msg .... but does the return code from the script bother you? If there was a nice error message but it returned code 1 to indicate an error?

**Comment by GregSutcliffe** [comment]
Error codes are good, it's easy to act on those. Current the user-add script returns zero even if a user is present. Perhaps we could standardise?

0) Added successfully
1) Error
2) No error but User/Site already configured

**Comment by jarofgreen** [comment]
So, I think as a first go I'd just like to fix the crash and make the scripts have error code 0 (fine) or 1 (error). Assigning specific meanings to error codes is something I'd like to do carefully,  and think through ramifications. Working on commit now.

**Comment by GregSutcliffe** [comment]
I see something got committed for this - is it ready to test from my perspective or is there more to do?

**Comment by jarofgreen** [comment]
It returns 0 (fine) or 1 (error) so go for it.

**Comment by GregSutcliffe** [comment]
Seems good - the admin user script isn't idempotent, but I'm not sure I'd expect it to be anyway. 

The createSite script doesn't crash any more, so thats good. I'm not 100% certain that it's idempotent, but I do see "Can any verified user edit: false" output from the script vs " Includes verified all users: Yes" in my Editors group on the sysadmin page, so I *think* it's fine.

Obviously I'm going to put code n the packaging to attempt to not run these unless we're sure it needs to, but it's good to know that it won't bomb if it gets run now ;)

**Comment by jarofgreen** [comment]
> but I do see "Can any verified user edit: false" output from the script vs " Includes verified all users: Yes" 

Not entirely sure what you mean by idempotent in this case, but to be clear: If the user / site already exists, then the create scripts will do nothing more and any attributes of the existing user / site will not be altered.

(Think this issue is ok to close now?)

**Comment by GregSutcliffe** [comment]
> idempotent
>
>   adj. (computing) Describing an action which, when performed multiple times, has no further effect on its subject after the first time it is performed.

That's cool, close it. If I see anything new I'll open new issues for it.
